### ISSUE TITLE
Requires FedACH/ Fedwire data file to use (question)?

### ISSUE THREAD

**Issue by jasan-s** [moov-io/fed#121]
For clarification , the docker image is useful to run solely http server, the actual data file link still needs to exist in order to make calls. 

I initially thought the lib helped run standalone validation for ACH and wire.

**Comment by adamdecaf** [comment]
Yes. The docker image can parse and serve the data files over a couple HTTP endpoints. The data file isn't public anymore and needs to be sourced from a Financial Institution.
