### ISSUE TITLE
Support env variables for string match thresholds

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/fed#30]
The [docs state environmental variables](https://github.com/moov-io/fed#configuration), but those aren't read out. Environmental variables split words with underscores.

- `ACH_JARO_WINKLER_SIMILARITY`
- `ACH_LEVENSHTEIN_SIMILARITY`

**Comment by bkmoovio** [comment]
Is the business need for this a bank defining lower or higher match rates for finding an ACH participant?   How does that help the business and what is the expected revenue generation from a bank being able to modify it?

**Comment by adamdecaf** [comment]
> I don't think 80% of our customer would use it. I actually don't think any customer would use it.

I agree and after noticing the readme offered advice on how to configure I didn't think we needed the readme note. 

I don't know why Go uses `GOPROXY` etc. `GO111MODULE` is temporary and going away in 1.13-ish

**Comment by adamdecaf** [comment]
I ended up removing those thresholds from OFAC. Instead sort and return the match percent for clients to decide.

**Comment by bkmoovio** [comment]
Do we really need that for FED?   I don't think a client would use that either.

**Comment by adamdecaf** [comment]
I think we're fine by just sorting results by their match percent.

**Comment by bkmoovio** [comment]
The results from JaroWinkler  with a match > 0.085 and Levenshtein with a match > 0.085 (Distinct) and are sorted by CustomerName.

	// CustomerName (36): FEDERAL RESERVE BANK
	CustomerName string `json:"customerName"

**Comment by bkmoovio** [comment]
I think it can be closed
