### ISSUE TITLE
ACHDirectory Fuzzy search on Bank Name

### ISSUE THREAD

**Issue by wadearnold** [moov-io/fed#6]
If a 1-2-1 match is not found in the Name search and optional fuzzy search could be used to handle misspelling or other issues if the name was not found. 

A package such as [Fuzzy Search](https://github.com/lithammer/fuzzysearch) could be added to the Bank Name field for better results. 

Additional packages to be tested [closesmatch](https://github.com/schollz/closestmatch)

**Comment by bkmoovio** [comment]
Used Levenstin and JaroWinkler for similarity
