### ISSUE TITLE
DefaultHeader can't be changed once APIClient is created

### ISSUE THREAD

**Issue by kalamity-linden** [moov-io/fed#69]
We have a use case where we would like to set `x-user-id` in the DefaultHeader for every call we make based on a user identifier. However, we're setting up the APIClient when the app starts up so we're not able to set the header at that time, since we want to track every user who makes these API calls. We would also like to avoid setting up a new client every time we want to issue an API call. Would it be possible to have a method attached to APIClient that adds key/value pairs to the DefaultHeader after the client has been created? Something similar to this: https://github.com/moov-io/fed/blob/master/client/client.go#L163. This functionality is also needed in the other APIs as well, ie. paygate, ofac, etc.

**Comment by adamdecaf** [comment]
@kalamity-linden Thanks for the idea! I created https://github.com/moov-io/fed/pull/70 to allow the optional `x-user-id`. I'll add it to the other apps (I think paygate is the only where it's required).

**Comment by adamdecaf** [comment]
I haven't make releases (or release candidates) of these yet, but the apps should accept an `x-user-id` header (or ignore it in the case of imagecashletter, wire, ACH) for logging and in the generated clients.

Let me know how this works for you. :)
