### ISSUE TITLE
Change Routing -> Name for Hatch Bank

### ISSUE THREAD

**Issue by zbruhnke** [moov-io/fed#83]
Hi there,

Currently this routing number `322286188` is listed as 

Racho Santa Fe Thrift & Loan but the bank has been renamed to Hatch Bank - would be great to update that in this file if possible

**Comment by adamdecaf** [comment]
These files are outdated, but used as examples. Your FI will be able to provide you with updated files.  We briefly mention this in the [usage section](https://github.com/moov-io/fed#usage). 

Perhaps we should make that more apparent?
